service: task-auth-api

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: UserInfo

functions:
  auth:
    handler: handler.handler
    events:
      - http:
          path: signup
          method: post
          cors: true
      - http:
          path: signin
          method: post
          cors: true
      - http:
          path: forgot-password
          method: post
          cors: true
      - http:
          path: reset-password
          method: post
          cors: true

resources:
  Resources:
    UserInfoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
